### ISSUE TITLE
Assign pages

### ISSUE THREAD

**Issue by shajoezhu** [pharmarug/pharmasug2024-r-workshop#8]
1 joe and liming
2 liming
3 joe
4 joe
5  liming
6 joe and liming

**Comment by clarkliming** [comment]
suggest we remove topic 6 (publication) and but mentions the importance of documentation and vignettes elsewhere. also let's keep a slot for open discussion ( people will be interested as they asked some other questions in the survey， including ai usage, R usage in clinical trials, etc).
